[tool.poetry]
name = "frontend"
version = "0.1.0"
description = ""
authors = ["vovquewa <kit.jke@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
flet = "^0.25.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
