"""Server Username

Revision ID: e08cbf40606a
Revises: fc8fc2d44f72
Create Date: 2024-12-04 18:13:37.942721

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e08cbf40606a'
down_revision: Union[str, None] = 'fc8fc2d44f72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('server', sa.Column('username', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('server', 'username')
    # ### end Alembic commands ###
